baseURL: "https://hugo-profile.netlify.app"
languageCode: "en-us"
title: "Hugo-profile"

googleanalytics: UA-167646412-8
disqusShortname: yourdisqusname
Paginate: 3

taxonomies:
  tag: "tags"
  category: "categories"

params:
  favicon: "/images/fav.png"
  description: "A high performance hugo theme for personal website. It is single page portfolio. It has blog."
  copyright: "2020"

  # Navbar Menus
  customMenus:
  - name: "Blog"
    Url: "/blog"
    
  # social
  name: "Gurusabarish"
  github: "https://github.com/gurusabarish"
  linkedin: "https://linkedin.com/in/gurusabarish"
  twitter: "https://twitter.com/gurusabarishh"
  instagram: "https://instagram.com/gurusabarishh"

  # Do things 
  usedothings: true
  usedefaultlogos: true

  thing1: "Python"
  thing2: "Machine learning"
  thing3: "Things for web"
  thing1_des: "I build something beautiful using Python."
  thing2_des: "I train robust models for various tasks."
  thing3_des: "I love to build things for web."

  # About
  profile_image: "/images/gurusabarish.webp"
  descripe_l1_person: "Hi, I'm Gurusabarish, a passionate web developer and ML engineer. 
  I tend to make use of modern web technologies to build websites that looks great, feels fantastic, and functions correctly."
  descripe_l2_person: "This is just a example for about section. You can easily change with the help of cofig file."
  job: "Web developer"
  resume: ""

Author:
  name: "Gurusabarish"
  website: "https://github.com/gurusabarish"
